apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api
      version: green
  template:
    metadata:
      labels:
        app: simple-api
        version: green
    spec:
      containers:
      - name: app
        image: akshaybhangale1/simple-api:blue
        ports:
        - containerPort: 8080
