apiVersion: v1
kind: Service
metadata:
  name: simple-api
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: simple-api
    version: blue   # switch to green when ready
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer