apiVersion: v1
kind: Service
metadata:
  name: simple-api
spec:
  type: LoadBalancer
  selector:
    app: simple-api
    version: blue   # switch to green when ready
  ports:
  - port: 80
    targetPort: 8080
